---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune-deploy
  labels:
    app: fortune
spec:
  replicas: 2
  selector:
    # pods that belong to this deployment
    matchLabels:
      app: fortune-pod
  template:
    metadata:
      name: fortune-pod
      labels:
        app: fortune-pod
    spec:
      containers:
      - name: fortune-container
        image: leowweiching/fortune:v2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-port
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fortune-svc
  labels:
    app: fortune
spec:
  type: ClusterIP
  selector:
    app: fortune-pod
  ports:
  - name: fortune-port
    port: 8080
    targetPort: http-port
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fortune-ing
  labels:
    app: fortune
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  # LoadBalancer external IP
  - host: fortune.167.172.6.35.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: fortune-svc
          servicePort: fortune-port
---