---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-cm
  labels:
    app: wordpress
data:
  WORDPRESS_DB_HOST: wpdb-cluster-mysql.wp.svc.cluster.local
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_NAME: wordpressdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deploy
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-pod
  template:
    metadata:
      labels:
        app: wp-pod
    spec:
      volumes:
      - name: wp-vol
        persistentVolumeClaim:
          claimName: wpdb-pvc
      containers:
      - name: wp-container
        image: wordpress
        imagePullPolicy: IfNotPresent
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wp-cm
              key: WORDPRESS_DB_HOST
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: wp-cm
              key: WORDPRESS_DB_USER
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wp-cm
              key: WORDPRESS_DB_NAME
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wpdb-secret
              key: ROOT_PASSWORD
        ports:
        - name: wp-port
          containerPort: 80
        volumeMounts:
        - name: wp-vol
          mountPath: /var/www/html
---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  labels:
    app: wordpress
spec:
  type: ClusterIP
  selector:
    app: wp-pod
  ports:
  - name: http-port
    port: 80
    targetPort: wp-port
---