apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpdb-pvc
  labels:
    app: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage